---
name: PhaseWorld
main: kim\present\phaseworld\PhaseWorld
version: 1.0.0
api: [ 5.0.0 ]
author: PresentKim
description: "High-performance virtual world instance loader with zero-IO instantiation and memory caching."
load: STARTUP
softdepend: [ CameraAPI ]
permissions:
  phaseworld.command:
    default: op
    description: "Allows using PhaseWorld commands"
virions:
  - SOF3/await-generator/master
  - presentkim-pm/libasynform/1.2.1
...
